server:
  port: 8081
  error:
    include-stacktrace: never

app:
  frontend:
    base-url: ${APP_FRONTEND_BASE_URL:http://localhost:8080}

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: 1403
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Flyway gerencia o esquema
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: user-service.email.queue

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.boot: INFO
    org.hibernate.SQL: DEBUG

security:
    jwt:
      secret: ${JWT_SECRET:12345678}