server:
  port: 8081
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: db123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Flyway gerencia o esquema
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.boot: INFO
    org.hibernate.SQL: DEBUG

security:
    jwt:
      secret: ${JWT_SECRET:12345678}